// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cawhohfpkzdtpvfewujj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhd2hvaGZwa3pkdHB2ZmV3dWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjcwNTMsImV4cCI6MjA2MjcwMzA1M30.AGzoh3x1xnh4LRdtt1HudGzhIfbR1FZFt7ytKb-dUxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);